### ISSUE TITLE
New app/website support

### ISSUE THREAD

**Issue by axel3rd** [axel3rd/mpg-grandslam-populator#27]
With new app/website (since **July, 19**), the current signin process throws: 

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 404 Not Found / Content: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.0</center>
</body>
</html>

        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:169)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:119)
        at org.blondin.mpg.AbstractClient.post(AbstractClient.java:111)
        at org.blondin.mpg.root.MpgClient.signIn(MpgClient.java:91)
        at org.blondin.mpg.root.MpgClient.build(MpgClient.java:49)
        at org.blondin.mpg.root.MpgClient.build(MpgClient.java:43)
        at org.blondin.mpg.Main.main(Main.java:65)
```

The APIs of mobile app should be used.

**Comment by axel3rd** [comment]
The switch from `/league/XXXLeagueId/ranking` is `/division/mpg_division_XXXLeagueId_X_Y/ranking/standings`.

**Comment by axel3rd** [comment]
To be tested, it requires 2 leagues in game minimum => we should wait a little.

**Comment by axel3rd** [comment]
@mansuydejean: Could we test a SNAPSHOT version before the release ? (need to wait this weekend, after L1 first day)
